### ISSUE TITLE
java.lang.NoSuchMethodError with idea 2021.2

### ISSUE THREAD

**Issue by fanf** [vsch/MissingInActions#26]
After upgrade to idea 2021.2, I get the following error message. I'm not sure about what it breaks, at least the "make control+arrow movement sane" still works.

```
java.lang.NoSuchMethodError: 'void com.vladsch.MissingInActions.util.MiaComboBoxAction$MiaComboBoxButton.updateButtonSize()'
	at com.vladsch.MissingInActions.util.MiaComboBoxAction$MiaComboBoxButton.updateUI(MiaComboBoxAction.java:474)
	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:131)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:85)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.<init>(ComboBoxAction.java:148)
	at com.vladsch.MissingInActions.util.MiaComboBoxAction$MiaComboBoxButton.<init>(MiaComboBoxAction.java:242)
	at com.vladsch.MissingInActions.util.MiaComboBoxAction.createComboBoxButton(MiaComboBoxAction.java:149)
	at com.vladsch.MissingInActions.util.MiaComboBoxAction.createComboBoxButton(MiaComboBoxAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createCustomComponent(ComboBoxAction.java:95)
	at com.intellij.openapi.actionSystem.ex.CustomComponentAction.createCustomComponent(CustomComponentAction.java:29)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.createCustomComponent(ActionToolbarImpl.java:387)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.getCustomComponent(ActionToolbarImpl.java:362)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.fillToolBar(ActionToolbarImpl.java:328)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.actionsUpdated(ActionToolbarImpl.java:1223)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.lambda$updateActionsImpl$3(ActionToolbarImpl.java:1147)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:84)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:16)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.jetbrains.concurrency.AsyncPromise.setResult(AsyncPromise.kt:149)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$13(ActionUpdater.java:279)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)```

**Comment by fanf** [comment]
OK, actually it seems to break the display of the top bar: anything that should appear after MiA buttons is not there: 
![image](https://user-images.githubusercontent.com/44649/130795119-2dbd7fc1-2016-4182-ab8d-abe666aaecc0.png)

Without MiA:
![image](https://user-images.githubusercontent.com/44649/130795797-354bbcb3-8cec-4dfc-b9c9-5c7f0be57203.png)

**Comment by fanf** [comment]
The problem in comment 2 is workaroundable by deleting "Missing in action" from settings > menu and toolbars > Navigation Bar Toolbar

**Comment by vsch** [comment]
Latest release https://github.com/vsch/MissingInActions/blob/master/dist/MissingInActions.1.8.212.4.zip is updated for 2021.2 compatibility. Will be available in JetBrains Marketplace after approval.
