### ISSUE TITLE
[PyCharm 2022.1] IllegalStateException: You must not register toolwindow programmatically so early. Rework code or use ToolWindowManager.invokeLater

### ISSUE THREAD

**Issue by todofixthis** [vsch/MissingInActions#29]
# Repro
## Details
* PyCharm v2022.1 (221.5080.212)
* Missing In Actions v1.8.2124)

## Steps
1. Launch PyCharm.

### Expected Behaviour
MiA Plugin loads as normal.

### Actual Behaviour
An exception occurs, and the plugin does not load.

> IllegalStateException: You must not register toolwindow programmatically so early. Rework code or use ToolWindowManager.invokeLater

# Exception Details
```
java.lang.IllegalStateException: You must not register toolwindow programmatically so early. Rework code or use ToolWindowManager.invokeLater
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.getToolWindowPaneIfInitialized(ToolWindowManagerImpl.kt:490)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow(ToolWindowManagerImpl.kt:928)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.registerToolWindow(BackendServerToolWindowManager.kt:89)
	at com.intellij.openapi.wm.ToolWindowManager.registerToolWindow(ToolWindowManager.kt:62)
	at com.vladsch.MissingInActions.BatchSearchReplaceToolWindow.<init>(BatchSearchReplaceToolWindow.java:57)
	at com.vladsch.MissingInActions.PluginProjectComponent.projectOpened(PluginProjectComponent.java:172)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt$openProject$$inlined$executeInEdtWithProgress$1$1$lambda$1.invoke(ProjectManagerExImpl.kt:503)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt$openProject$$inlined$executeInEdtWithProgress$1$1$lambda$1.invoke(ProjectManagerExImpl.kt)
	at com.intellij.serviceContainer.ComponentManagerImpl.processInitializedComponents(ComponentManagerImpl.kt:1324)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt$openProject$$inlined$executeInEdtWithProgress$1$1.run(ProjectManagerExImpl.kt:611)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt$openProject$$inlined$executeInEdtWithProgress$1.run(ProjectManagerExImpl.kt:460)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:96)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Let me know if you have any questions and/or if there is any further information I can provide.

**Comment by todofixthis** [comment]
Possibly relevant: I found this commit in another plugin that referenced the same issue as above:
https://github.com/antlr/intellij-plugin-v4/commit/252ac626d74542b06409449984455389131aace6

**Comment by dan-earle** [comment]
Problem also present in Intellij IDEA 2022.1

**Comment by caesay** [comment]
Same issue in Rider 2022.1.1

**Comment by j-a-s-o-n-g** [comment]
Same for intellij IDEA 2022.1.1

**Comment by j-a-s-o-n-g** [comment]
Btw this isn't just a bug but entire plugin no longer functions in latest IDE's @vsch

**Comment by KnifeFed** [comment]
Not only that, it messes up so bad that the whole IDE becomes practically unusable until the plugin is disabled.

**Comment by todofixthis** [comment]
In the meantime, I'm trying out https://github.com/MohammadMD1383/Actionable as a potential substitute/replacement; it seems to provide many of the same features as MIA 😇

I still ❤️ MIA and would love to keep using it — if #30 gets resolved I'm still super keen to jump in and create a PR to fix this `IllegalStateException` issue 😺

**Comment by MohammadMD1383** [comment]
Hi, I'm not sure if I can provide a fix for this, but you may help me bring these features to the Actionable plugin.

These days I'm really busy but if you can create PRs it's welcomed!

**Comment by j-a-s-o-n-g** [comment]
@todofixthis Would you help me port over some long-missed functionality to Actionable since I don't know Java?

**Comment by vsch** [comment]
**Uploaded new version which takes care of 2022 compatibility**, works with IJ 2022.1 and CLION 2022.3.2. Have not tried it with any 2023.1 EAP yet.
